// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDatbqYvbCD-2O3k5QtNaXWIX5Pftv9DbU',
    appId: '1:523857761597:web:b2f87bfc2f78326a056154',
    messagingSenderId: '523857761597',
    projectId: 'matracking-276bd',
    authDomain: 'matracking-276bd.firebaseapp.com',
    databaseURL: 'https://matracking-276bd-default-rtdb.firebaseio.com',
    storageBucket: 'matracking-276bd.firebasestorage.app',
    measurementId: 'G-XSF50T8DFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ45g4sH9t47EeUkM_aqOujJXWPD7VowU',
    appId: '1:523857761597:android:1b5d408bb3b93f6c056154',
    messagingSenderId: '523857761597',
    projectId: 'matracking-276bd',
    databaseURL: 'https://matracking-276bd-default-rtdb.firebaseio.com',
    storageBucket: 'matracking-276bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjqwZcaPQjWm0_fmEHiVi6CMMckBsx840',
    appId: '1:523857761597:ios:4423c83011dcb0fa056154',
    messagingSenderId: '523857761597',
    projectId: 'matracking-276bd',
    databaseURL: 'https://matracking-276bd-default-rtdb.firebaseio.com',
    storageBucket: 'matracking-276bd.firebasestorage.app',
    iosBundleId: 'com.example.matracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjqwZcaPQjWm0_fmEHiVi6CMMckBsx840',
    appId: '1:523857761597:ios:4423c83011dcb0fa056154',
    messagingSenderId: '523857761597',
    projectId: 'matracking-276bd',
    databaseURL: 'https://matracking-276bd-default-rtdb.firebaseio.com',
    storageBucket: 'matracking-276bd.firebasestorage.app',
    iosBundleId: 'com.example.matracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDatbqYvbCD-2O3k5QtNaXWIX5Pftv9DbU',
    appId: '1:523857761597:web:0428840287a1dc13056154',
    messagingSenderId: '523857761597',
    projectId: 'matracking-276bd',
    authDomain: 'matracking-276bd.firebaseapp.com',
    databaseURL: 'https://matracking-276bd-default-rtdb.firebaseio.com',
    storageBucket: 'matracking-276bd.firebasestorage.app',
    measurementId: 'G-45WQBKTN80',
  );
}
